export const RESERVATION_WINDOW_MINUTES = 10;
export const RESERVATION_WINDOW_MS = RESERVATION_WINDOW_MINUTES * 60 * 1000;
export const DEFAULT_CURRENCY = 'USD';
export const MAX_EXPIRY_RELEASE_BATCH = 50;
export const DEFAULT_PAGE_SIZE = 25;
